[package]
name = "oxide-infrastructure"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
jsonwebtoken.workspace = true
serde.workspace = true
uuid.workspace = true
thiserror.workspace = true
