[package]
name = "oxide-shared-types"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
validator.workspace = true

utoipa = { workspace = true, optional = true }

[features]
default = []
full = ["utoipa"]