[package]
name = "oxide-api"
version.workspace = true
edition.workspace = true

[dependencies]
tokio.workspace = true
dotenvy.workspace = true
actix-web.workspace = true
actix-cors.workspace = true
utoipa.workspace = true
utoipa-swagger-ui.workspace = true
oxide-data = {path = "../oxide-data"}
