[package]
name = "oxide-data"
version.workspace = true
edition.workspace = true

[dependencies]
sqlx.workspace = true
oxide-domain = {path="../oxide-domain"}
oxide-business = {path="../oxide-business"}
thiserror.workspace = true
serde.workspace = true
