[package]
name = "oxide-config"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
figment.workspace = true

[lints]
workspace = true
